// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkgmgctavfqpxwfnprgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrZ21nY3RhdmZxcHh3Zm5wcmd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0ODczMTYsImV4cCI6MjA3MzA2MzMxNn0.eE7cTl6unGqG9pYK__QAqfS7zqaxMPy1ZXmzE3Fxwio";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});